name: Build and Push 5e-database-ru Docker image

on:
  workflow_dispatch:

jobs:
  build-and-push-db:
    name: Build and Push MongoDB image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - id: lower
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ github.repository_owner }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push MongoDB image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ steps.lower.outputs.lowercase }}/5e-database-ru:latest
